import React from 'react'
import { Html,  Main, NextScript } from 'next/document'
import Head from 'next/head'

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <title>Token Faucet</title>
        <meta name="description" content="Generated by @alephium/cli init" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
